{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-config
  namespace: {{ include "app.namespace" . }}
data:
  {{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
