name: Await Manual Approval

on:
  workflow_call:

jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - run: echo "Awaiting manual approval to continue..."
