name: Build Docker Image

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      dockerfile: { required: false, type: string, default: 'Dockerfile' }
      context: { required: false, type: string, default: '.' }
      push: { required: false, type: boolean, default: true }
    outputs:
      image_tag:
        value: ${{ jobs.build.outputs.image_tag }}
      image_url:
        value: ${{ jobs.build.outputs.image_url }}
    secrets:
      REGISTRY: { required: true }

jobs:
  build:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
      image_url: ${{ steps.set_tag.outputs.image_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        id: set_tag
        run: |
          echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "image_url=${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build \
            -f ${{ inputs.dockerfile }} \
            -t ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ github.sha }} \
            ${{ inputs.context }}

      - name: Push Docker image
        if: inputs.push == true
        run: docker push ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ github.sha }}

      - name: Save image artifact
        if: inputs.push == false
        run: docker save -o image.tar ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ github.sha }}

      - name: Upload Docker image artifact
        if: inputs.push == false
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: image.tar
          retention-days: 14
