name: Deploy to Staging

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      image_tag: { required: true, type: string }
    secrets:
      REGISTRY: { required: true }

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Validate Inputs
        run: |
          if [ -z "${{ inputs.app_name }}" ] || [ -z "${{ inputs.image_tag }}" ]; then
            echo "Missing inputs" && exit 1
          fi

      - name: Ensure namespace exists
        run: |
          ns=${{ inputs.app_name }}-staging
          k get ns $ns || k create ns $ns

      - uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ inputs.image_tag }}

      - name: Load and push image
        run: |
          docker load -i image.tar
          docker push ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ inputs.image_tag }}

      - name: Deploy via Ansible
        run: |
          ssh ansible@solace \
            "ansible-playbook ~/ansible/playbooks/deploy-staging-bluegreen.yaml \
              -e app_name=${{ inputs.app_name }} \
              -e git_sha=${{ inputs.image_tag }} \
              -e registry=${{ secrets.REGISTRY }}"
