name: Deploy Application

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      image_tag: { required: true, type: string }
      environment: { required: true, type: string }
      playbook: { required: false, type: string, default: 'deploy.yaml' }
    secrets:
      REGISTRY: { required: true }

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy with Ansible
        run: |
          ssh ansible@solace \
            "ansible-playbook ~/ansible/playbooks/${{ inputs.playbook }} \
              -e app_name=${{ inputs.app_name }} \
              -e git_sha=${{ inputs.image_tag }} \
              -e registry=${{ secrets.REGISTRY }} \
              -e env=${{ inputs.environment }}"
