name: Prepare environment

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      environment: { required: true, type: string }

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run Terraform for environment
        run: |
          cd terraform/environments/${{ inputs.environment }}
          tofu init
          tofu apply -auto-approve -var="app_name=${{ inputs.app_name }}"
