name: Prepare environment

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      environment: { required: true, type: string }

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenTofu
        run: |
          curl -sSfL https://get.opentofu.org/install.sh | sh
          echo "$HOME/.opentofu/bin" >> $GITHUB_PATH

      - name: Run Terraform for environment
        working-directory: infra/terraform/environments/${{ inputs.environment }}
        run: |
          tofu init
          tofu apply -auto-approve -var="app_name=${{ inputs.app_name }}"
