name: Prepare environment

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup kubeconfig for Terraform
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Terraform Init + Apply
        working-directory: infra/terraform/environments/${{ inputs.environment }}
        run: |
          echo "Deploying app: ${{ inputs.app_name }} to environment: ${{ inputs.environment }}"
          tofu init
          tofu apply -auto-approve -var-file="terraform.tfvars"
