name: Promote to prod

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      image_tag: { required: true, type: string }
    secrets:
      SSH_PRIVATE_KEY: { required: true }
      REGISTRY: { required: true }

jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Await manual approval
        run: echo "Approved for prod."

  promote:
    needs: approval
    runs-on: self-hosted
    steps:
      - name: Validate Inputs
        run: |
          if [ -z "${{ inputs.app_name }}" ] || [ -z "${{ inputs.image_tag }}" ]; then
            echo "Missing inputs" && exit 1
          fi

      - uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ inputs.image_tag }}

      - name: Load, retag, and push image
        run: |
          docker load -i image.tar
          docker tag ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ inputs.image_tag }} \
                     ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:prod
          docker push ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:prod

      - name: Deploy to prod
        run: |
          ssh ansible@solace \
            "ansible-playbook ~/ansible/playbooks/deploy-prod-bluegreen.yaml \
              -e app_name=${{ inputs.app_name }} \
              -e git_sha=prod \
              -e registry=${{ secrets.REGISTRY }}"