name: Promote Docker Image

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
      source_tag: { required: true, type: string }
      target_tag: { required: true, type: string }
    secrets:
      REGISTRY: { required: true }

jobs:
  promote:
    runs-on: self-hosted

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ inputs.source_tag }}

      - name: Load, retag, and push
        run: |
          docker load -i image.tar
          docker tag ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ inputs.source_tag }} \
                     ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ inputs.target_tag }}
          docker push ${{ secrets.REGISTRY }}/${{ inputs.app_name }}:${{ inputs.target_tag }}
